steps:
  # - name: Run behat tests
  #   plugin: Shell
  #   command:  'cd $SRC_DIR ; pwd ; ls -al ; composer install ; bin/behat '
  - name: Run composer
    plugin: Script
    script: |
      cd $SRC_DIR ; pwd ;ls-la; /usr/local/bin/composer self-update; composer update ;

  - name: Behat tests
    plugin: Script
    script: |

      chmod +x $SRC_DIR/probo_behat.sh
      $SRC_DIR/probo_behat.sh
  #    cd $SRC_DIR ; ls -la; probo_behat.sh
  # - name: Behat tests
  #   plugin: Script
  #   script:
  #      cd $SRC_DIR/Behat_Probo/ ./bin/behat

  # - name: Echo pwd
  #   plugin: Script
  #   script: |
  #     cd /Behat_Probo/features
  #     pwd


  # - name: Behat tests
  #   command: 'cd Behat_Probo ; ./vendor/bin/behat'

  # - name: Run behat tests
  #   plugin: Shell
  #   command: 'composer install ; ./bin/behat'
