steps:
  # - name: Run behat tests
  #   plugin: Shell
  #   command:  'cd $SRC_DIR ; pwd ; ls -al ; composer install ; bin/behat '
  - name: Behat tests
    plugin: Script
    script: |
      pwd ; composer install ; cd $SRC_DIR/probo_behat.sh
  #
  # - name: Behat tests
  #   plugin: Script
  #   script: |
  #      cd $SRC_DIR/Behat_Probo/ ./bin/behat

  # - name: Echo pwd
  #   plugin: Script
  #   script: |
  #     cd /Behat_Probo/features
  #     pwd


  # - name: Behat tests
  #   command: 'cd Behat_Probo ; ./vendor/bin/behat'

  # - name: Run behat tests
  #   plugin: Shell
  #   command: 'composer install ; ./bin/behat'
