steps:
  - name: Hello World
    command: 'echo "Get started with probo checks!"'

  - name: Hello Again
    command:
      pwd; ls -al; pwd; cd ../; pwd; ls -al;

  # - name: Echo pwd
  #   plugin: Script
  #   script: |
  #     cd /Behat_Probo/features
  #     pwd


  # - name: Behat tests
  #   command: 'cd Behat_Probo ; ./vendor/bin/behat'

  # - name: Run behat tests
  #   plugin: Shell
  #   command: 'composer install ; ./bin/behat'
