steps:
  # - name: Hello World
  #   command: 'echo "Get started with probo checks!"'
  # #
  # # - name: Hello Again
  # #   command:
  # #     pwd; ls -al; pwd; cd ../; pwd; ls -al;
  - name: Run behat tests
    plugin: Shell
    command:  'ls -al'

  - name: Behat tests
    plugin: Script
    script: |
       cd $SRC_DIR/Behat_Probo && ./behat.sh
  #
  # - name: Behat tests
  #   plugin: Script
  #   script: |
  #      cd $SRC_DIR/Behat_Probo/ ./bin/behat

  # - name: Echo pwd
  #   plugin: Script
  #   script: |
  #     cd /Behat_Probo/features
  #     pwd


  # - name: Behat tests
  #   command: 'cd Behat_Probo ; ./vendor/bin/behat'

  # - name: Run behat tests
  #   plugin: Shell
  #   command: 'composer install ; ./bin/behat'
